#! /bin/bash

##Status bar

while true; do
xsetroot -name "$(date)"
sleep 1m
done &
##Aplicaciones inicio
feh --bg-scale /home/alc111/repos/DWM/wallpaper/dwmbackground.png &
picom --experimental-backends &
setxkbmap -layout es &
pnmixer &
nm-applet &
dunst &
exec dwm
